#screen resolution
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#player values
PLAYER_RADIUS = 20
LINE_WIDTH = 2

#movement control
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

#asteroid constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#player shooting behavior
SHOT_RADIUS = 5 #radius of each shot
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3 #cooldown between player shots